apply null check
offMomySon/spring_reservation_project pull request #17
Opened 2020-08-27 18:31 UTC by offMomySon

2020-08-27 18:41 UTC, offMomySon commented on src/main/java/kr/or/connect/reservation/controller/ReservationApiController.java
> +	@NonNull
I don't know if I need to put nonNull on the controller.

2020-08-27 18:41 UTC, offMomySon commented on src/main/java/kr/or/connect/reservation/controller/ReservationApiController.java
> +	public void storeEmailInfoIfNeeded(@NonNull List<ReservationResponseRs> responseList,@NonNull HttpSession session,@NonNull String reservationEmail) {
I don't know if I need to attach it to every param.

2020-08-27 18:41 UTC, offMomySon commented on src/main/java/kr/or/connect/reservation/dto/ReservationResponseRs.java
> +	public void setDisplayInfo(@NonNull DisplayInfoRs displayInfoRs) {
I am not sure if NonNull is necessary for the set function of the model.
Can you give me some advice?

2020-08-27 20:22 UTC, offMomySon commented on src/main/java/kr/or/connect/reservation/service/impl/ReservationServiceImpl.java
> +	@NonNull
@NonNull 을 method 에 걸었을때,
아래의 request 를 보내서 체크를 해봤지만 예상과는 다르게 에러를 출력하지않습니다
http://localhost:8080/reservation/api/reservations

```	
        @NonNull
	@Override
	@Transactional(readOnly = false)
	public ReservationRequestRs addReservation(@NonNull ReservationRequestRs rsvRequest) {
		setNewDate(rsvRequest);
		ReservationInfo reservationInfo = makeReservationInfo(rsvRequest);

		log.debug("rsv = {}", reservationInfo);

		reservationInfo = rsvRep.save(reservationInfo);

		insertPriceList(reservationInfo.getId(), rsvRequest.getPrices());

		return null;
	}```

2020-08-28 02:28 UTC, joey-yoonsung requested changes

2020-08-28 02:28 UTC, joey-yoonsung commented on src/main/java/kr/or/connect/reservation/controller/CategoryApiController.java
> +import lombok.NonNull;
Do not use null-related annotation in lombok. 
Please use jsr-305 library in here. https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

2020-08-28 02:28 UTC, joey-yoonsung commented on src/main/java/kr/or/connect/reservation/dto/ReservationResponseRs.java
> +	public void setDisplayInfo(@NonNull DisplayInfoRs displayInfoRs) {
I should be.

2020-08-28 02:28 UTC, joey-yoonsung commented on src/main/java/kr/or/connect/reservation/service/impl/ReservationServiceImpl.java
> +	@NonNull
Nonnull library 를 바꿔서 해보세요.

2020-08-28 02:28 UTC, joey-yoonsung commented on src/main/java/kr/or/connect/reservation/controller/ReservationApiController.java
> +	public void storeEmailInfoIfNeeded(@NonNull List<ReservationResponseRs> responseList,@NonNull HttpSession session,@NonNull String reservationEmail) {
Use [ParametersAreNonnullByDefault](https://www.javadoc.io/doc/com.google.code.findbugs/jsr305/3.0.1/javax/annotation/ParametersAreNonnullByDefault.html)

2020-08-28 02:30 UTC, joey-yoonsung commented on src/main/java/kr/or/connect/reservation/controller/ReservationApiController.java
> +	@NonNull
Do not need.

2020-08-29 06:15 UTC, merged